export default {
  // https://hrxmukwvym.us-east-1.awsapprunner.com/v1/
  // https://eaqbkijgtb.us-east-1.awsapprunner.com/v1/
  BASE_URL: "https://eaqbkijgtb.us-east-1.awsapprunner.com/v1/",
  LOGIN: "login",
  FORGOT: "forgot",
  LOGIN_ME: "users/me/",
  TOKEN: "token",
  LOGIN_MFA: "login/mfa",
  VERIFY_OTP: "verify-otp",
  RESET_PASSWORD: "reset-pass",
  SECURITY_QUESTIONS: "login/security",
  SECURITY_QUESTIONS_NEXT: "login/security/next",
  LOGIN_WEBULL: "login/webull",
  REGISTER: "",
  SERVER: "server/", // keep trailing slash
  ANALYST: "server/{serverId}/analyst",
  SERVERDATA: "server/data",
  // CURRENT_POSITION: "server/option_orders",
  CURRENT_POSITION: "server/webull/get_options_positions",
  // STANDING_OPTIONS_ORDER: "server/standing_option_orders",
  // PLACE_ORDER_OPTION: "server/place_option_order",
  STANDING_OPTIONS_ORDER: "server/webull/get_options_order",
  PLACE_ORDER_OPTION: "server/webull/place_options_order",
  ENTER_NEW_TRADE: "server/stock/check/{enternewtrade}",
  // EXPIRATION_DATE: "server/stock/expiration/{stock}",
  EXPIRATION_DATE: "server/options/expiration/{stock}",
  LIMIT: "server/stock/limit",
  TRANSACTION_HISTORY: "server/transaction_history",
  // CANCEL_ORDER: "server/option/cancel/{order_id}",
  // MODIFY_ORDER: "server/modify_option_order",
  CANCEL_ORDER: "server/webull/cancel_order/{order_id}",
  MODIFY_ORDER: "server/webull/modify_options_order",
  UPDATE_PROFILE: "users/me/",
};
